### ISSUE TITLE
ModuleNotFoundError: No module named 'diskover_cache' when using BAM plugin

### ISSUE THREAD

**Issue by LordBonkerz** [diskoverdata/diskover-community#102]
python3 diskover.py -i diskover-storage /beegfs-storage/ -f

Traceback (most recent call last):
  File "diskover.py", line 35, in <module>
    from diskover_elasticsearch import elasticsearch_connection, \
  File "/opt/diskover/diskover_elasticsearch.py", line 135, in <module>
    plugins = load_plugins()
  File "/opt/diskover/diskover_helpers.py", line 489, in load_plugins
    plugin_info['spec'].loader.exec_module(plugin_module)
  File "/opt/diskover/plugins/baminfo/__init__.py", line 48, in <module>
    import diskover_cache as mi_cache

**Comment by shirosaidev** [comment]
This has been fixed in v2.0.4-1 of Diskover ME
