### ISSUE TITLE
Raise error | IndexError: list index out of range

### ISSUE THREAD

**Issue by doubleailes** [diskoverdata/diskover-community#82]
I was just walking a mount point. Nothing special.

```Traceback (most recent call last):
  File "diskover.py", line 2268, in <module>
    post_crawl_tasks()
  File "diskover.py", line 2030, in post_crawl_tasks
    upload_stats()
  File "diskover.py", line 1995, in upload_stats
    size = es.search(index=index, doc_type='directory', body=body)['hits']['hits'][0]['_source']['filesize']
IndexError: list index out of range
```

**Comment by shirosaidev** [comment]
is this still an issue?

**Comment by doubleailes** [comment]
Yes

**Comment by shirosaidev** [comment]
What is the full cli command you are using to run diskover? Is the index getting created in elasticsearch and is there data getting added? Can you view the index in Kibana or diskover-web okay?

**Comment by doubleailes** [comment]
I reinstall everything with a new python3.8 install and work great!

**Comment by doubleailes** [comment]
Bad news. Like the monthy python would say about a rabbot **it did it again**

Here is more information:
```
python /srv/dockers/web/diskover/diskover.py -d /mnt/GFS/PRODS -i diskover-2020-09-18 -a -O -A


   ___       ___       ___       ___       ___       ___       ___       ___
  /\  \     /\  \     /\  \     /\__\     /\  \     /\__\     /\  \     /\  \
 /::\  \   _\:\  \   /::\  \   /:/ _/_   /::\  \   /:/ _/_   /::\  \   /::\  \
/:/\:\__\ /\/::\__\ /\:\:\__\ /::-"\__\ /:/\:\__\ |::L/\__\ /::\:\__\ /::\:\__\
\:\/:/  / \::/\/__/ \:\:\/__/ \;:;-",-" \:\/:/  / |::::/  / \:\:\/  / \;:::/  /
 \::/  /   \:\__\    \::/  /   |:|  |    \::/  /   L;;/__/   \:\/  /   |:\/__/
  \/__/     \/__/     \/__/     \|__|     \/__/               \/__/     \|__|
                                      v1.5.1.0
                                      https://shirosaidev.github.io/diskover
                                      Bringing light to the darkness.
                                      Support diskover on Patreon or PayPal :)

    
2020-09-18 07:52:24,691 [INFO][diskover] Using config file: /srv/dockers/web/diskover/diskover.cfg
2020-09-18 07:52:24,694 [INFO][diskover] Checking es index: diskover-2020-09-18
Drop existing index? [y/n]: y
2020-09-18 07:52:31,265 [WARNING][diskover] es index exists, deleting
2020-09-18 07:52:31,390 [INFO][diskover] Creating es index
2020-09-18 07:52:32,241 [INFO][diskover] Tuning ES index settings for crawl
2020-09-18 07:52:32,315 [INFO][diskover] Adding disk space info to es index
2020-09-18 07:52:32,382 [INFO][diskover] Found 16 diskover RQ worker bots
2020-09-18 07:52:32,382 [INFO][diskover] Enqueueing crawl to diskover worker bots for /mnt/GFS/PRODS...
2020-09-18 07:52:32,382 [INFO][diskover] Worker bots set to auto-tag (-A)
2020-09-18 07:52:32,382 [INFO][diskover] Sending adaptive batches to worker bots (-a)
2020-09-18 07:52:32,382 [INFO][diskover] Starting crawl using 80 treewalk threads (maxdepth None)
| Crawling (Queue: 0, 1144.284 dirs/sec) Elapsed Time: 0:00:15                                                                                                                               
| |           #                                                                                                                                                     | 0 Elapsed Time: 0:04:48
2020-09-18 07:57:36,749 [INFO][diskover] Finished crawling in 0d:0h:05m:04s, dirs walked 16372 (53.791 dirs/sec)
2020-09-18 07:57:36,791 [INFO][diskover] Waiting for diskover worker bots to be done with any jobs in rq...
2020-09-18 07:57:36,819 [INFO][diskover] Getting diskover bots to calculate directory sizes (maxdepth None)...
/ Calculating (Queue: 0) Elapsed Time: 0:00:00                                                                                                                                               2020-09-18 07:57:36,821 [INFO][diskover] Searching for all directory docs in diskover-2020-09-18...
2020-09-18 07:57:37,248 [INFO][diskover] Found 650 directory docs
| Calculating (Queue: 0) Elapsed Time: 0:00:00                                                                                                                                               
| |          #                                                                                                                                                      | 0 Elapsed Time: 0:00:01
2020-09-18 07:57:38,294 [INFO][diskover] Finished calculating 650 directory sizes in 0d:0h:00m:01s
2020-09-18 07:57:38,344 [INFO][diskover] Setting ES index settings back to defaults
2020-09-18 07:57:38,428 [INFO][diskover] Force merging ES index...
2020-09-18 07:57:39,269 [INFO][diskover] Optimizing ES index... this could take a while... (-O)
Traceback (most recent call last):
  File "/srv/dockers/web/diskover/diskover.py", line 2267, in <module>
    post_crawl_tasks()
  File "/srv/dockers/web/diskover/diskover.py", line 2029, in post_crawl_tasks
    upload_stats()
  File "/srv/dockers/web/diskover/diskover.py", line 1994, in upload_stats
    size = es.search(index=index, doc_type='directory', body=body)['hits']['hits'][0]['_source']['filesize']
IndexError: list index out of range
```

**Comment by doubleailes** [comment]
The index is create in ES. And visible in the web interface but incomplete.

**Comment by doubleailes** [comment]
i had time to run in debug finaly:
```log
2020-09-26 16:36:41,071 [INFO][diskover] batchsize set to: 50
2020-09-26 16:36:41,082 [INFO][diskover] enqueued batchsize: 50 (batchsize: 50)
2020-09-26 16:36:41,083 [INFO][diskover] batchsize set to: 50
2020-09-26 16:36:41,094 [INFO][diskover] enqueued batchsize: 50 (batchsize: 50)
2020-09-26 16:36:41,094 [INFO][diskover] batchsize set to: 50
2020-09-26 16:36:41,105 [INFO][diskover] enqueued batchsize: 50 (batchsize: 50)
2020-09-26 16:36:41,105 [INFO][diskover] batchsize set to: 50
2020-09-26 16:36:41,116 [INFO][diskover] enqueued batchsize: 50 (batchsize: 50)
2020-09-26 16:36:41,117 [INFO][diskover] batchsize set to: 50
2020-09-26 16:36:41,120 [DEBUG][urllib3.util.retry] Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2020-09-26 16:36:41,122 [DEBUG][urllib3.connectionpool] http://localhost:9200 "GET /_search/scroll?scroll=1m HTTP/1.1" 200 240
2020-09-26 16:36:41,123 [INFO][elasticsearch] GET http://localhost:9200/_search/scroll?scroll=1m [status:200 request:0.003s]
2020-09-26 16:36:41,123 [DEBUG][elasticsearch] > {"scroll_id": "DXF1ZXJ5QW5kRmV0Y2gBAAAAAAAACAMWdW1MNVptOGtTMVd4YzNNVWxISUhQUQ=="}
2020-09-26 16:36:41,123 [DEBUG][elasticsearch] < {"_scroll_id":"DXF1ZXJ5QW5kRmV0Y2gBAAAAAAAACAMWdW1MNVptOGtTMVd4YzNNVWxISUhQUQ==","took":1,"timed_out":false,"terminated_early":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":865,"max_score":1.0,"hits":[]}}
2020-09-26 16:36:41,126 [INFO][diskover] Found 865 directory docs
2020-09-26 16:36:42,163 [INFO][diskover] Finished calculating 865 directory sizes in 0d:0h:00m:01s
2020-09-26 16:36:42,163 [DEBUG][urllib3.util.retry] Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2020-09-26 16:36:42,239 [DEBUG][urllib3.connectionpool] http://localhost:9200 "POST /diskover-20200926-gfs/crawlstat HTTP/1.1" 201 178
2020-09-26 16:36:42,239 [INFO][elasticsearch] POST http://localhost:9200/diskover-20200926-gfs/crawlstat [status:201 request:0.076s]
2020-09-26 16:36:42,240 [DEBUG][elasticsearch] > {"path": "/mnt/GFS/PRODS", "state": "finished_dircalc", "crawl_time": 54.814962, "indexing_date": "2020-09-26T14:36:42.163338"}
2020-09-26 16:36:42,240 [DEBUG][elasticsearch] < {"_index":"diskover-20200926-gfs","_type":"crawlstat","_id":"AXTK2Dk1atzIJIIT4fRd","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"created":true}
2020-09-26 16:36:42,240 [INFO][diskover] Setting ES index settings back to defaults
2020-09-26 16:36:42,240 [DEBUG][urllib3.util.retry] Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2020-09-26 16:36:42,311 [DEBUG][urllib3.connectionpool] http://localhost:9200 "PUT /diskover-20200926-gfs/_settings HTTP/1.1" 200 21
2020-09-26 16:36:42,311 [INFO][elasticsearch] PUT http://localhost:9200/diskover-20200926-gfs/_settings [status:200 request:0.071s]
2020-09-26 16:36:42,312 [DEBUG][elasticsearch] > {"index": {"refresh_interval": "1s", "number_of_replicas": 0, "translog.flush_threshold_size": "512mb"}}
2020-09-26 16:36:42,312 [DEBUG][elasticsearch] < {"acknowledged":true}
2020-09-26 16:36:42,312 [INFO][diskover] Force merging ES index...
2020-09-26 16:36:42,312 [DEBUG][urllib3.util.retry] Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2020-09-26 16:36:43,162 [DEBUG][urllib3.connectionpool] http://localhost:9200 "POST /diskover-20200926-gfs/_forcemerge HTTP/1.1" 200 49
2020-09-26 16:36:43,163 [INFO][diskover] Optimizing ES index... this could take a while... (-O)
2020-09-26 16:36:43,163 [DEBUG][urllib3.util.retry] Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2020-09-26 16:36:45,532 [DEBUG][urllib3.connectionpool] http://localhost:9200 "POST /diskover-20200926-gfs/_forcemerge?max_num_segments=1 HTTP/1.1" 200 49
2020-09-26 16:36:45,533 [DEBUG][urllib3.util.retry] Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2020-09-26 16:36:45,537 [DEBUG][urllib3.connectionpool] http://localhost:9200 "POST /diskover-20200926-gfs/_refresh HTTP/1.1" 200 49
2020-09-26 16:36:45,537 [DEBUG][urllib3.util.retry] Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2020-09-26 16:36:45,541 [DEBUG][urllib3.connectionpool] http://localhost:9200 "GET /diskover-20200926-gfs/directory/_count HTTP/1.1" 200 73
2020-09-26 16:36:45,542 [DEBUG][urllib3.util.retry] Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2020-09-26 16:36:45,545 [DEBUG][urllib3.connectionpool] http://localhost:9200 "GET /diskover-20200926-gfs/file/_count HTTP/1.1" 200 75
2020-09-26 16:36:45,545 [DEBUG][urllib3.util.retry] Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2020-09-26 16:36:45,549 [DEBUG][urllib3.connectionpool] http://localhost:9200 "GET /diskover-20200926-gfs/directory/_search HTTP/1.1" 200 134
Traceback (most recent call last):
  File "/srv/dockers/web/diskover/diskover.py", line 2267, in <module>
    post_crawl_tasks()
  File "/srv/dockers/web/diskover/diskover.py", line 2029, in post_crawl_tasks
    upload_stats()
  File "/srv/dockers/web/diskover/diskover.py", line 1994, in upload_stats
    size = es.search(index=index, doc_type='directory', body=body)['hits']['hits'][0]['_source']['filesize']
IndexError: list index out of range
```

**Comment by shirosaidev** [comment]
It looks like there is an issue getting the rootdir doc size from the es index. Do you see in diskover-web or kibana the correct size for the rootdir doc directory for /mnt/GFS/PRODS directory?

**Comment by doubleailes** [comment]
In the "Disk Space Overview" i can see the root dir size.
Is there somewhere where i can see this size to confirm you the information?

**Comment by shirosaidev** [comment]
Do a search in diskover-web for all directories and see if that directory (the top rootdir one /mnt/GFS/PRODS) is listed and has the correct size, items counts. If you can, please attach screenshot of diskover-web all directory search results.

**Comment by doubleailes** [comment]
The top directory ` /mnt/GFS/PRODS` is not listed

**Comment by shirosaidev** [comment]
With the same user you run diskover.py and the worker bots, can you run `ls -la /mnt/GFS/PRODS`. Do you get a directory listing? The user you are using, does it have permission to stat the files/dirs in that directory? Check the worker bots are running python3, same version of python as you are running diskover.py. Take a look here at python version https://github.com/shirosaidev/diskover/wiki/Troubleshooting and other troubleshooting.

**Comment by doubleailes** [comment]
> With the same user you run diskover.py and the worker bots, can you run ls -la /mnt/GFS/PRODS. Do you get a directory listing?
Yes
>The user you are using, does it have permission to stat the files/dirs in that directory? 
Yes it's root user ( i know it's not safe but i'm in testing phase)
> Check the worker bots are running python3, same version of python as you are running diskover.py.
I run diskover in virtualenv and start the bot with the sh maybe it's from here.
Can override the python path in the sh. From what i saw it use the current python exe which is my virtualenv python nope?

**Comment by doubleailes** [comment]
So i run Diskover and bots in the same specific virtualenv, with the exact same version of python 3.8.5
Same issues.

**Comment by shirosaidev** [comment]
when you run `ls -la /mnt/GFS/PRODS` do you see any permission denied lines?

**Comment by shirosaidev** [comment]
can you please send output of `ls -la /mnt/GFS` if you can

**Comment by doubleailes** [comment]
Off course ! I removed some informations.
```bash
ls -la /mnt/GFS/PRODS
total 6
drwxrwxrwx 12 root   root           12 Oct  2 10:58 .
drwxr-xr-x  6 root   root            6 Mar 12  2020 ..
drwxrwxrwx  XXX
drwxrwxrwx  XXX
drwxrwxrwx  XXX
drwxrwxrwx  XXX
drwxrwxr-x  XXX
drwxrwxrwx  XXX
dr-xrwx---  XXX
drwxrwxrwx  XXX
drwxrwxr-x  XXX
drwxrwxrwx  XXX
```
```bash
ls -la /mnt/GFS
total 6
drwxr-xr-x   6 root root    6 Mar 12  2020 .
drwxr-xr-x.  6 root root 4096 Sep 10 19:28 ..
drwxrwxr-x   3 root  root     3 Dec  3  2019 DEMO
drwxrwxrwx  12 root root   12 Oct  2 10:58 PRODS
drwxrwxrwx   2 root root    2 Mar 12  2020 SANDBOX
```

**Comment by shirosaidev** [comment]
with adding the additional cli flags I mentioned above, do you see /mnt/GFS/PRODS directory doc in the index now?

**Comment by shirosaidev** [comment]
I recommend to stop all the bots, run 1 bot in foreground so you can see its log output (or redirect log to disk) and see if there are any warnings/errors when trying to index the top rootdir doc PRODS. Also run diskover.py in debug mode and see if there are any errors/warnings related to that directory doc.

**Comment by doubleailes** [comment]
So i made multiple tests in my spare time along this week.
The only case i'm able to reproduce the bug. It's when i'm running more than 3 bots.
And i don't seem to have error in the bot log.
I'm gonna try new test this week end.
