### ISSUE TITLE
No module names 'six' and 'pkg_resources'

### ISSUE THREAD

**Issue by alexanderphoenix** [diskoverdata/diskover-community#88]
Hi,

I've just tried to run Diskover on docker as per the docker-compose example on [dockerhub](https://hub.docker.com/r/linuxserver/diskover)

At first it seems to run but once I check the logs, it repeats over and over the following traceback:
```
Traceback (most recent call last):
  File "/app/diskover/diskover.py", line 29, in <module>
    import progressbar
  File "/usr/lib/python3.8/site-packages/progressbar/__init__.py", line 3, in <module>
    from .utils import (
  File "/usr/lib/python3.8/site-packages/progressbar/utils.py", line 7, in <module>
    from python_utils.time import timedelta_to_seconds, epoch, format_time
  File "/usr/lib/python3.8/site-packages/python_utils/time.py", line 1, in <module>
    import six
ModuleNotFoundError: No module named 'six'
Traceback (most recent call last):
  File "/usr/bin/rq-dashboard", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```

Anyone encountered this before?

Running on `Docker version 19.03.6, build 369ce74a3c` with this docker-compose:
```
version: '3'

services:
  diskover:
    image: linuxserver/diskover
    container_name: diskover
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - ES_USER=elastic
      - ES_PASS=changeme
      - RUN_ON_START=true
      - USE_CRON=true
    volumes:
      - ${DOCKER_HOME}/diskover/config:/config
      - ${DOCKER_HOME}/diskover/data:/data
    ports:
      - 8085:80
      - 9181:9181
      - 9999:9999
    deploy:
      resources:
        limits:
          memory: 4096M
    restart: unless-stopped
    depends_on:
      - elasticsearch
      - redis

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    volumes:
      - ${DOCKER_HOME}/docker/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - ${DOCKER_HOME}/docker/redis:/data
```

The memory limit won't work on docker-compose v3 as I'm not running docker swarm.

Any help is greatly appreciated

**Comment by Torqu3Wr3nch** [comment]
I'm seeing the same thing in the linuxserver.io Docker image as well. Looks like someone else is seeing this too: [ Diskover spits out errors: ModuleNotFoundError: No module named 'six' / 'pkg_resources' #38](https://github.com/linuxserver/docker-diskover/issues/38)

Issue started sometime in the past two weeks (could have been up to three weeks). My last successful run was on 11/2/20.

**Comment by alexanderphoenix** [comment]
Thank you for confirming this is a widespread issue.

**Comment by davidhorrock0949** [comment]
Use docker tag v1.5.0.13-ls82 until it gets fixed
