### ISSUE TITLE
ValueError: too many values to unpack (expected 4)

### ISSUE THREAD

**Issue by ultiplyr** [diskoverdata/diskover-community#97]
Running a scan over NFS on a particularly "bushy" directory tree we have though I don't know if that is relevant.
The error that comes back in the terminal is
`2021-12-09 08:45:48,708 - diskover - INFO - [ThreadPoolExecutor-0_10] finished crawling /d3/TARGET/ESP (235312 dirs, 48648360 files, 32.77 TB) in 0d:11h:21m:01s
Traceback (most recent call last):
  File "diskover.py", line 945, in <module>
    crawl(tree_dir)
  File "diskover.py", line 617, in crawl
    raise result.exception()
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "diskover.py", line 562, in crawl_thread
    size, size_du, file_count, dir_count = get_tree_size(thread, root, top, top, docs, depth, maxdepth)
  File "diskover.py", line 271, in get_tree_size
    s, sdu, fc, dc = get_tree_size(thread, root, top, entry.path, docs, depth+1, maxdepth)
  File "diskover.py", line 271, in get_tree_size
    s, sdu, fc, dc = get_tree_size(thread, root, top, entry.path, docs, depth+1, maxdepth)
  File "diskover.py", line 271, in get_tree_size
    s, sdu, fc, dc = get_tree_size(thread, root, top, entry.path, docs, depth+1, maxdepth)
  [Previous line repeated 2 more times]
ValueError: too many values to unpack (expected 4)`

Last lines from the log file are:
`2021-12-09 08:45:46,055 - diskover - INFO - CRAWL STATS (path /d3/TARGET, files 348488240, dirs 2411037, elapsed 15:20:44.517786, perf 6390.723 inodes/s, 2 paths still scanning ['/d3/TARGET/ESP', '/d3/TARGET/EAL'], memory usage 116.81 MB)
2021-12-09 08:45:46,055 - diskover - INFO - ES UPLOAD STATS (path /d3/TARGET, uploaded 350898516 docs, elapsed 15:20:44.517786, perf 6351.735 docs/s)
2021-12-09 08:45:48,708 - diskover - INFO - [ThreadPoolExecutor-0_10] finished crawling /d3/TARGET/ESP (235312 dirs, 48648360 files, 32.77 TB) in 0d:11h:21m:01s`

last lines from the warning logs are:
`2021-12-08 17:26:44,284 - diskover_warn - WARNING - [ThreadPoolExecutor-0_0] OS ERROR: [Errno 13] Permission denied: '/d3/TARGET/ASSETDEV/testchar/SHARED/MODEL/char/max_head/wpsd_shapes/md/alembic_v025'
2021-12-09 01:56:58,632 - diskover_warn - WARNING - [ThreadPoolExecutor-0_9] OS ERROR: [Errno 2] No such file or directory: '/d3/TARGET/EAL/0090jed/SHARED/IMG/rig/eal0090jed_head_render_v008.hmc'
`

**Comment by shirosaidev** [comment]
Does that error happen on every crawl or just that one directory tree? Have you tried crawling that same directory tree again, do you get that same error? Are you running CE v2.0-rc2?

**Comment by ultiplyr** [comment]
So far, it appears to be just this tree. Running the same scan again now. 
It occurs to me that I had two scans looking at different targets. So I'll run this solo.
And it looks like this is rc1. I'll get ahold of rc2.

**Comment by ultiplyr** [comment]
Installed rc2. This happened now on a different tree, though the initial tree I tried made it through another scan successfully.

**Comment by shirosaidev** [comment]
found the bug that is causing this, will be patched in rc3

**Comment by shirosaidev** [comment]
@ultiplyr this has been patched in rc3, please update and let us know if this is fixed now
